openapi: 3.0.0
info:
  title: Muving API - OpenAPI 3.0
  description: |
    ### Transfer your playlist seamlessly!
  contact:
    email: dukov.ko.dev@gmail.com
  version: 1.0.0
servers:
  - url: https://muving.site/api/v1
tags:
  - name: playlist
    description: Everything about playlist
  - name: song
    description: Everything about song
  - name: user
    description: Operations about user

paths:
  /playlist/verifyLink:
    post:
      tags:
        - playlist
      summary: Verify if the user's link is valid
      description: Verify the link is valid in certain service or not
      requestBody:
        description: Source service's name, input link by the user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Link'
            examples:
              example1:
                summary: Melon link
                value:
                  sourceService: 'Melon'
                  link: 'https://www.melon.com/mymusic/playlist/mymusicplaylistview_inform.htm?plylstSeq=538112402'
              example2:
                summary: Genie link
                value:
                  sourceService: 'Genie'
                  link: 'https://www.genie.co.kr/myMusic/myfolder?mxnm=45897890&bgsq=316676011'
              example3:
                summary: Vibe link
                value:
                  sourceService: 'Vibe'
                  link: 'https://vibe.naver.com/mylist/61516063'
              example4:
                summary: Bugs link
                value:
                  sourceService: 'Bugs'
                  link: 'https://music.bugs.co.kr/nextbugs/share/myalbum/229150'
              example5:
                summary: FLO link
                value:
                  sourceService: 'FLO'
                  link: '[FLO]20240501(1)https://flomuz.io/s/r.h007FjGIB'
        required: true
      responses:
        '200':
          description: Link validation succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: Invalid link
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The link is invalid'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /playlist/getPlaylistWithOAuth:
    post:
      tags:
        - playlist
      summary: Get user's playlists with OAuth
      description: If the source service supports OAuth, use this API.
      security:
        - BearerAuth: []
      requestBody:
        description: Source service's name
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SourceName'
        required: true
      responses:
        '200':
          description: Successfully received user's playlist data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SourceDataArray'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Bad request'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /playlist/addPlaylistWithOAuth:
    post:
      tags:
        - playlist
      summary: Add playlist to the destination service that supports OAuth
      description: If the destination service supports OAuth, use this API.
      security:
        - BearerAuth: []
      requestBody:
        description: Either provide sourceName, playlistId, playlistTitle, or playlistLink with destinationName
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Addplaylist'
            examples:
              example1:
                summary: If the source service supports OAuth
                value:
                  SourceName: 'YouTube Music'
                  destinationName: 'Spotify'
                  playlistId: 289373
                  playlistTitle: 'MyPlaylist'
              example2:
                summary: If the source service doesn't supports OAuth
                value:
                  SourceName: 'Melon'
                  destinationName: 'Spotify'
                  playlistLink: 'https://www.melon.com/mymusic/playlist/mymusicplaylistview_inform.htm?plylstSeq=538112402'
        required: true
      responses:
        '200':
          description: Successfully created new playlist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaylistCreatedOAuth'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Bad request'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /playlist/addPlaylistWithoutOAuth:
    post:
      tags:
        - playlist
      summary: Add playlist to the destination service that doesn't support OAuth
      description: If the destination service doesn't support OAuth, use this API.
      security:
        - BearerAuth: []
      requestBody:
        description: Source service's name, playlist id, playlist title, destination service's name
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Addplaylist'
            examples:
              example1:
                summary: If the source service supports OAuth
                value:
                  SourceName: 'YouTube Music'
                  destinationName: 'Melon'
                  playlistId: 289373
                  playlistTitle: 'MyPlaylist'
              example2:
                summary: If the source service doesn't supports OAuth
                value:
                  SourceName: 'Melon'
                  destinationName: 'Vibe'
                  playlistLink: 'https://www.melon.com/mymusic/playlist/mymusicplaylistview_inform.htm?plylstSeq=538112402'
        required: true
      responses:
        '200':
          description: 'Successfully created new playlist'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneratedPlaylistLink'
              examples:
                example1:
                  summary: Melon link
                  value:
                    generatedLink: 'https://www.melon.com/mymusic/playlist/mymusicplaylistview_inform.htm?plylstSeq=538112402'
                example2:
                  summary: Genie link
                  value:
                    generatedLink: 'https://www.genie.co.kr/myMusic/profileRecommandDetail?bgsq=316676011&axnm=45897890'
                example3:
                  summary: Vibe link
                  value:
                    generatedLink: 'https://vibe.naver.com/mylist/61516063'
                example4:
                  summary: Bugs link
                  value:
                    generatedLink: 'https://music.bugs.co.kr/nextbugs/share/myalbum/229149'
                example5:
                  summary: FLO link
                  value:
                    generatedLink: 'https://flomuz.io/s/r.h007FjGIB'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Bad request'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /playlist/userPlaylist:
    get:
      tags:
        - playlist
      summary: Get user's transfered playlists
      description: Get user's transfered playlists, five at a time
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/PageNum'
      responses:
        '200':
          description: User's playlist, up to five
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaylistArray'
        '404':
          description: Cannot find user's playlist
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Playlist not found'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'
    put:
      tags:
        - playlist
      summary: Modify user's playlist description
      security:
        - BearerAuth: []
      requestBody:
        description: Playlist description
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaylistModify'
        required: true
      responses:
        '200':
          description: The playlist's description has modified
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Successfully modified description'
        '404':
          description: Cannot find playlist
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Playlist not found'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /playlist/userPlaylist/{playlistId}:
    delete:
      tags:
        - playlist
      summary: Delete user's playlist
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/PlaylistId'
      responses:
        '200':
          description: Successfully deleted the playlist
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Successfully deleted'
        '404':
          description: Cannot find playlist
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Playlist not found'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /song/search:
    get:
      tags:
        - song
      summary: Search songs in available services
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/SearchQuery'
      responses:
        '200':
          description: Successfully found result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongSearchResponse'
        '404':
          description: Cannot find the song anywhere
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Song not found'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /song/recent:
    get:
      tags:
        - song
      summary: Get user's recent search results, up to five
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully found result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongSearchResponseArray'
        '404':
          description: Cannot find the user's search log
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Search log not found'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/signUpWithOAuth:
    post:
      tags:
        - user
      summary: Sign up using OAuth
      description: If successfully signed up, creates new user account, then return JWT
      requestBody:
        description: Service provider's name, authorization code
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpWithOAuthBody'
        required: true
      responses:
        '201':
          description: Successfully signed up
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/signInWithOAuth:
    post:
      tags:
        - user
      summary: Sign in using OAuth
      description: If successfully signed in, return JWT
      requestBody:
        description: Service provider's name, authorization code
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpWithOAuthBody'
        required: true
      responses:
        '200':
          description: Successfully signed in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTResponse'
        '404':
          description: Cannot find user account
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Cannot find user account'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/checkEmail:
    post:
      tags:
        - user
      summary: Check if the user's email address is a duplicate
      requestBody:
        description: Email address
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailAddress'
        required: true
      responses:
        '200':
          description: The email address is not a duplicate
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Valid email address'
        '400':
          description: The email address is a duplicate
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Invalid email address'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/verifyEmail:
    post:
      tags:
        - user
      summary: Verify the user's email address is valid by sending authentication code
      requestBody:
        description: Email address
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailAddress'
        required: true
      responses:
        '200':
          description: Authentication code has sent to the email address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationCode'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/signUpWithEmail:
    post:
      tags:
        - user
      summary: Sign up using email address
      requestBody:
        description: Email address, encrpyted password
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/EmailAddress'
                - $ref: '#/components/schemas/EncryptedPassword'
        required: true
      responses:
        '201':
          description: Successfully signed up
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/signInWithEmail:
    post:
      tags:
        - user
      summary: Sign in using email address
      requestBody:
        description: Email address, encrpyted password
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/EmailAddress'
                - $ref: '#/components/schemas/EncryptedPassword'
        required: true
      responses:
        '200':
          description: Successfully signed up
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTResponse'
        '404':
          description: Cannot find user account
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Cannot find user account'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/info:
    get:
      tags:
        - user
      summary: Get user's information
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully fetched the user's information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/logout:
    delete:
      tags:
        - user
      summary: Delete the user's JWT at server-side
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully deleted the user's JWT in Redis
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: "user's JWT deleted"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/integrateOAuth:
    post:
      tags:
        - user
      summary: Connect to a new OAuth provider
      security:
        - BearerAuth: []
      requestBody:
        description: Service provider's name, authorization code
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpWithOAuthBody'
        required: true
      responses:
        '201':
          description: Successfully connected to the provider
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Successfully connected to the provider'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
          example: 'The link is valid'

    PlaylistModify:
      type: object
      properties:
        playlistId:
          type: integer
          example: 283740
        description:
          type: string
          example: 'This is modified description'

    SourceName:
      type: object
      properties:
        sourceName:
          type: string
          example: 'YouTube Music'

    PlaylistCreatedOAuth:
      type: object
      properties:
        message:
          type: string
          example: 'Playlist created successfully'

    GeneratedPlaylistLink:
      type: object
      properties:
        generatedLink:
          type: string
          example: 'https://www.melon.com/mymusic/playlist/mymusicplaylistview_inform.htm?plylstSeq=538066453'

    Addplaylist:
      type: object
      properties:
        sourceName:
          type: string
          example: 'YouTube Music'
        destinationName:
          type: string
          example: 'Spotify'
        playlistId:
          type: integer
          example: 289373
        playlistTitle:
          type: string
          example: 'MyPlaylist'
        playlistLink:
          type: string
          example: 'https://www.melon.com/mymusic/playlist/mymusicplaylistview_inform.htm'

    SourceData:
      type: object
      properties:
        playlistId:
          type: integer
          example: 289373
        playlistTitle:
          type: string
          example: 'MyPlaylist'

    SourceDataArray:
      type: array
      items:
        $ref: '#/components/schemas/SourceData'

    Link:
      type: object
      properties:
        sourceService:
          type: string
          example: 'Melon'
        link:
          type: string
          example: 'https://www.melon.com/mymusic/playlist/mymusicplaylistview_inform.htm?plylstSeq=538066453'

    Playlist:
      type: object
      properties:
        id:
          type: integer
          example: 28634
        name:
          type: string
          example: 'MyPlaylist'
        sourceName:
          type: string
          example: 'Spotify'
        destinationName:
          type: string
          example: 'Melon'
        generatedLink:
          type: string
          example: 'https://www.melon.com/mymusic/playlist/mymusicplaylistview_inform.htm'
        description:
          type: string
          example: 'This is my playlist.'

    PlaylistArray:
      type: array
      items:
        $ref: '#/components/schemas/Playlist'
      maxItems: 5

    SongSearchResponseArray:
      type: array
      items:
        $ref: '#/components/schemas/SongSearchResponse'
      maxItems: 5

    SongSearchResponse:
      type: object
      properties:
        query:
          type: string
          example: 'carrie europe'
        results:
          type: array
          items:
            $ref: '#/components/schemas/SongSearchResult'
          maxItems: 8

    SongSearchResult:
      type: object
      properties:
        service:
          type: string
          example: 'Melon'
        result:
          type: array
          maxItems: 3
          items:
            $ref: '#/components/schemas/Track'

    Track:
      type: object
      properties:
        id:
          type: integer
          example: 1
        artist:
          type: string
          example: 'Europe'
        track:
          type: string
          example: 'Carrie'
        album:
          type: string
          example: 'The Final Countdown'

    SignUpWithOAuthBody:
      type: object
      properties:
        serviceProvider:
          type: string
          example: 'YouTube Music'
        authorizationCode:
          type: string
          example: 'Authorization code'

    JWTResponse:
      type: object
      properties:
        accessToken:
          type: string
          example: 'Access token'
        refreshToken:
          type: string
          example: 'Refresh token'

    EmailAddress:
      type: object
      properties:
        address:
          type: string
          example: 'example@gmail.com'

    EncryptedPassword:
      type: object
      properties:
        password:
          type: string
          example: 'Encrypted password'

    AuthenticationCode:
      type: object
      properties:
        authenticationCode:
          type: string
          example: '652437'

    UserInfo:
      type: object
      properties:
        img:
          type: string
          example: 'img link'
        name:
          type: string
          example: 'Muving user'

  parameters:
    PageNum:
      name: pageNum
      in: query
      required: true
      schema:
        type: integer
        example: 6
    PlaylistId:
      name: playlistId
      in: path
      required: true
      schema:
        type: integer
        example: 428682
    SearchQuery:
      name: searchQuery
      in: query
      required: true
      schema:
        type: string
        example: 'carrie europe'
